import os

content = (
    "{% extends 'base.html' %}\n"
    "{% block content %}\n"
    "<div class=\"row justify-content-center py-5\">\n"
    "    <div class=\"col-md-7 col-lg-6\">\n"
    "        <div class=\"d-flex align-items-center mb-4\">\n"
    "            <a href=\"{% url 'public_profile' request.user.username %}\" class=\"btn btn-sm btn-outline-secondary me-3\">\n"
    "                <i class=\"bi bi-arrow-left\"></i>\n"
    "            </a>\n"
    "            <h2 class=\"fw-bold mb-0\">Edit Your Profile</h2>\n"
    "        </div>\n"
    "        <div class=\"card border-0 shadow-sm\">\n"
    "            <div class=\"card-body p-4\">\n"
    "                <form method=\"post\" enctype=\"multipart/form-data\">\n"
    "                    {% csrf_token %}\n"
    "                    <div class=\"text-center mb-4\">\n"
    "                        <div id=\"avatar-preview-wrapper\" class=\"mx-auto mb-3\" style=\"width:110px;height:110px;\">\n"
    "                            {% if form.instance.avatar %}\n"
    "                            <img id=\"avatar-preview\" src=\"{{ form.instance.avatar.url }}\" class=\"rounded-circle border shadow\" style=\"width:110px;height:110px;object-fit:cover;\" alt=\"Avatar\">\n"
    "                            {% else %}\n"
    "                            <div id=\"avatar-initials\" class=\"rounded-circle bg-primary text-white d-flex align-items-center justify-content-center fw-bold\" style=\"width:110px;height:110px;font-size:2.5rem;\">\n"
    "                                {{ request.user.username|first|upper }}\n"
    "                            </div>\n"
    "                            <img id=\"avatar-preview\" src=\"\" class=\"rounded-circle border shadow d-none\" style=\"width:110px;height:110px;object-fit:cover;\" alt=\"Avatar\">\n"
    "                            {% endif %}\n"
    "                        </div>\n"
    "                        <label for=\"{{ form.avatar.id_for_label }}\" class=\"btn btn-outline-primary btn-sm rounded-pill px-4\">\n"
    "                            <i class=\"bi bi-camera me-1\"></i> Upload Photo\n"
    "                        </label>\n"
    "                        <div class=\"d-none\">{{ form.avatar }}</div>\n"
    "                        <div class=\"form-text mt-1\">JPG, PNG. Max 5 MB.</div>\n"
    "                    </div>\n"
    "                    <hr class=\"my-3\">\n"
    "                    <div class=\"mb-3\">\n"
    "                        <label class=\"form-label fw-semibold\">Bio</label>\n"
    "                        {{ form.bio }}\n"
    "                        {% if form.bio.errors %}<div class=\"text-danger small mt-1\">{{ form.bio.errors }}</div>{% endif %}\n"
    "                    </div>\n"
    "                    <div class=\"mb-4\">\n"
    "                        <label class=\"form-label fw-semibold\">Phone <span class=\"text-muted fw-normal\">(optional)</span></label>\n"
    "                        {{ form.phone }}\n"
    "                        {% if form.phone.errors %}<div class=\"text-danger small mt-1\">{{ form.phone.errors }}</div>{% endif %}\n"
    "                    </div>\n"
    "                    <button type=\"submit\" class=\"btn btn-primary w-100 py-2 fw-semibold\">\n"
    "                        <i class=\"bi bi-check-circle me-2\"></i>Save Changes\n"
    "                    </button>\n"
    "                </form>\n"
    "            </div>\n"
    "        </div>\n"
    "    </div>\n"
    "</div>\n"
    "<script>\n"
    "    const avatarInput = document.getElementById('{{ form.avatar.id_for_label }}');\n"
    "    const avatarPreview = document.getElementById('avatar-preview');\n"
    "    const avatarInitials = document.getElementById('avatar-initials');\n"
    "    if (avatarInput) {\n"
    "        avatarInput.addEventListener('change', function () {\n"
    "            if (this.files && this.files[0]) {\n"
    "                const reader = new FileReader();\n"
    "                reader.onload = e => {\n"
    "                    avatarPreview.src = e.target.result;\n"
    "                    avatarPreview.classList.remove('d-none');\n"
    "                    if (avatarInitials) avatarInitials.classList.add('d-none');\n"
    "                };\n"
    "                reader.readAsDataURL(this.files[0]);\n"
    "            }\n"
    "        });\n"
    "    }\n"
    "</script>\n"
    "{% endblock %}\n"
)

target = r'c:\Users\MIDHUN\.gemini\antigravity\playground\tensor-cassini\templates\core\profile_edit.html'
with open(target, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

with open(target, 'r') as f:
    lines = f.readlines()
print(f'Written {len(lines)} lines OK')
for i, l in enumerate(lines, 1):
    if '{%' in l or '%}' in l:
        print(f'  Line {i}: {l.rstrip()}')
